### ISSUE TITLE
Make Your First Open Source Contribution

### ISSUE THREAD

**Issue by MadhavBahlMD** [Logic-Xcution/Kickoff-To-Open-Source#2]
Add Your Name, Username and bio

**Comment by MadhavBahlMD** [comment]
I want to work on this

**Comment by rashinkafernando** [comment]
Added rpfernando as a contributor.

**Comment by rashinkafernando** [comment]
Added rpfernando as a contributor

**Comment by aaditkamat** [comment]
This repository does not adhere to [the Hacktoberfest standards](https://hacktoberfest.digitalocean.com/details#spam), so I think that the hacktoberfest label should be removed.

**Comment by MadhavBahlMD** [comment]
Thanks for letting me know @aaditkamat
